# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: project_rpg
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 5444:5444
